include { ORTHOFINDER } from "${projectDir}/modules/infer_orthology/orthofinder"

workflow INFER_ORTHOLOGY {

    take:
    proteomes
    user_tree

    main:
    ORTHOFINDER(proteomes)
    
    /*
     * Select the tree used by downstream analyses.
     *
     * The user-provided tree has priority. When user_tree is false,
     * use the rooted species tree generated by OrthoFinder.
     */
    if (params.tree) {
        println "Using user-provided tree for downstream analyses"
        tree = user_tree
    } else {
        println "Using OrthoFinder-generated tree for downstream analyses"
        tree = ORTHOFINDER.out.species_tree
    }

    tree.view()
    emit:
    orthofinder_results = ORTHOFINDER.out.results
    tree = tree
}
