include { ORTHOFINDER                       } from "${projectDir}/modules/infer_orthology/orthofinder"
include { NORMALIZE_SPECIES_NAMES           } from "${projectDir}/modules/infer_orthology/normalize_species_names"
include { ADD_ORTHOGROUPS_TO_ANNOTATIONS    } from "${projectDir}/modules/downstream_analysis/add_orthogroups_to_annotations"
include { ANNOTATE_ORTHOGROUP_FUNCTIONS     } from "${projectDir}/modules/infer_orthology/annotate_orthogroup_functions"

workflow INFER_ORTHOLOGY {

    take:
    proteomes
    user_tree
    taxonomy 
    annotations

    main:
    ORTHOFINDER(proteomes)
    
    ORTHOFINDER.out.orthogroups
        .concat(ORTHOFINDER.out.gene_count, ORTHOFINDER.out.unassigned_genes, ORTHOFINDER.out.tree)
        .set { orthofinder_results }

    NORMALIZE_SPECIES_NAMES(orthofinder_results, taxonomy)

    NORMALIZE_SPECIES_NAMES.out
        .filter { file -> file.name == "Orthogroups.tsv" }
        .set { orthogroups }

    NORMALIZE_SPECIES_NAMES.out
        .filter { file -> file.name == "Orthogroups.GeneCount.tsv" }
        .set { gene_count }

    NORMALIZE_SPECIES_NAMES.out
        .filter { file -> file.name == "Orthogroups_UnassignedGenes.tsv" }
        .set { unassigned_genes }

    /*
     * Add orthogroup information to the GO-annotated GFF files for each genome.
     */
    ADD_ORTHOGROUPS_TO_ANNOTATIONS(annotations, orthogroups)

    /*
     * Annotate orthogroups
     */
    ADD_ORTHOGROUPS_TO_ANNOTATIONS.out
        .map { name, meta, annotations -> annotations }
        .collect()
        .set { annotations_with_orthogroups }

    ANNOTATE_ORTHOGROUP_FUNCTIONS(annotations_with_orthogroups)

    /*
     * Select the tree used by downstream analyses.
     *
     * The user-provided tree has priority. When user_tree is false,
     * use the rooted species tree generated by OrthoFinder.
     */
    if (params.tree) {
        println "Using user-provided tree for downstream analyses"
        tree = user_tree

    } else {
        println "Using OrthoFinder-generated tree for downstream analyses"
        NORMALIZE_SPECIES_NAMES.out
            .filter { file -> file.name == "SpeciesTree_rooted.txt" }
            .set { tree }
    }   
            
    emit:
    orthogroups = orthogroups
    gene_count = gene_count
    unassigned_genes = unassigned_genes
    tree = tree
}
